import { NewExercise } from "../schema";

/**
 * Seed data for 50 yoga/stretch exercises
 * Images are stored as identifiers that map to local assets
 * See utils/exercise-images.ts for the actual image mapping
 */
export const EXERCISES_SEED_DATA: NewExercise[] = [
  {
    id: "crossed-leg-forward-fold",
    title: "Crossed Leg Forward Fold",
    image: "crossed-leg-forward-fold",
    difficulties: [1, 2, 3],
  },
  {
    id: "butterfly-stretch",
    title: "Butterfly Stretch",
    image: "butterfly-stretch",
    difficulties: [1, 2, 3],
  },
  {
    id: "harmstring-stretch-right-side",
    title: "Harmstring Stretch (Right)",
    image: "harmstring-stretch-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "harmstring-stretch-left-side",
    title: "Harmstring Stretch (Left)",
    image: "harmstring-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "yogi-squat",
    title: "Yogi Squat",
    image: "yogi-squat",
    difficulties: [1, 2, 3],
  },
  {
    id: "extended-puppy-pose",
    title: "Extended Puppy Pose",
    image: "extended-puppy-pose",
    difficulties: [1, 2, 3],
  },
  {
    id: "lunge-plus-upper-body-opener-right-side",
    title: "Lunge + Upper Body Opener (Right leg)",
    image: "lunge-plus-upper-body-opener-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "lunge-plus-upper-body-opener-left-side",
    title: "Lunge + Upper Body Opener (Left leg)",
    image: "lunge-plus-upper-body-opener-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "camel-stretch",
    title: "Camel Stretch",
    image: "camel-stretch",
    difficulties: [1, 2, 3],
  },
  {
    id: "child-s-pose",
    title: "Child's Pose",
    image: "child-s-pose",
    difficulties: [1, 2, 3],
  },
  {
    id: "seated-forward-fold",
    title: "Seated Forward Fold",
    image: "seated-forward-fold",
    difficulties: [1, 2, 3],
  },
  {
    id: "harmstring-stretch-right-side",
    title: "Harmstring Stretch (Right leg)",
    image: "harmstring-stretch-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "harmstring-stretch-left-side",
    title: "Harmstring Stretch (Left leg)",
    image: "harmstring-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "gate-pose-bends-right-side",
    title: "Gate Pose Bends (Right leg)",
    image: "gate-pose-bends-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "gate-pose-bends-left-side",
    title: "Gate Pose Bends (Left leg)",
    image: "gate-pose-bends-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "pigeon-pose-left-side",
    title: "Pigeon Pose (Left leg)",
    image: "pigeon-pose-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "pigeon-pose-right-side",
    title: "Pigeon Pose (Right leg)",
    image: "pigeon-pose-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "cobra",
    title: "Cobra",
    image: "cobra",
    difficulties: [1, 2, 3],
  },
  {
    id: "downward-dog",
    title: "Downward Dog",
    image: "downward-dog",
    difficulties: [1, 2, 3],
  },
  {
    id: "seated-quad-stretch-left-side",
    title: "Seated Quad Stretch (Left leg)",
    image: "seated-quad-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "seated-quad-stretch-right-side",
    title: "Seated Quad Stretch (Right leg)",
    image: "seated-quad-stretch-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "wide-leg-side-stretch-left-side",
    title: "Wide Leg Side Stretch (Left leg)",
    image: "wide-leg-side-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "wide-leg-side-stretch-right-side",
    title: "Wide Leg Side Stretch (Right leg)",
    image: "wide-leg-side-stretch-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "forward-fold-harmstring-stretch",
    title: "Forward Fold Harmstring Stretch",
    image: "forward-fold-harmstring-stretch",
    difficulties: [1, 2, 3],
  },
  {
    id: "double-legged-quad-stretch",
    title: "Double Legged Quad Stretch",
    image: "double-legged-quad-stretch",
    difficulties: [3],
  },
  {
    id: "frog-stretch",
    title: "Frog Stretch",
    image: "frog-stretch",
    difficulties: [1, 2, 3],
  },
  {
    id: "baby-pose",
    title: "Baby Pose",
    image: "baby-pose",
    difficulties: [1, 2, 3],
  },
  {
    id: "baby-pose-left-side",
    title: "Left Side Baby Pose",
    image: "baby-pose-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "baby-pose-right-side",
    title: "Right Side Baby Pose",
    image: "baby-pose-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "thread-the-needle-right-side",
    title: "Thread the Needle (Right)",
    image: "thread-the-needle-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "thread-the-needle-left-side",
    title: "Thread the Needle (Left)",
    image: "thread-the-needle-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "runners-stretch-right-side",
    title: "Runners Stretch (Right leg)",
    image: "runners-stretch-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "runners-stretch-left-side",
    title: "Runners Stretch (Left leg)",
    image: "runners-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "kneeling-harmstring-stretch-left-side",
    title: "Kneeling Harmstring Stretch (Left leg)",
    image: "kneeling-harmstring-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "kneeling-harmstring-stretch-right-side",
    title: "Kneeling Harmstring Stretch (Right leg)",
    image: "kneeling-harmstring-stretch-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "adductor-stretch-left-side",
    title: "Adductor Stretch (Left leg)",
    image: "adductor-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "adductor-stretch-right-side",
    title: "Adductor Stretch (Right leg)",
    image: "adductor-stretch-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "tricep-stretch-left-side",
    title: "Tricep Stretch (Left)",
    image: "tricep-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "tricep-stretch-right-side",
    title: "Tricep Stretch (Right)",
    image: "tricep-stretch-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "shoulder-stretch-left-side",
    title: "Shoulder Stretch (Left)",
    image: "shoulder-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "shoulder-stretch-right-side",
    title: "Shoulder Stretch (Right)",
    image: "shoulder-stretch-right-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "hanging-harmstring-stretch",
    title: "Hanging Harmstring Stretch",
    image: "hanging-harmstring-stretch",
    difficulties: [1, 2, 3],
  },
  {
    id: "side-neck-stretch-left-side",
    title: "Side Neck Stretch (Left)",
    image: "side-neck-stretch-left-side",
    difficulties: [1, 2, 3],
  },
  {
    id: "side-neck-stretch-right-side",
    title: "Side Neck Stretch (Right)",
    image: "side-neck-stretch-right-side",
    difficulties: [1, 2, 3],
  },
];
