import { NewExercise } from "../schema";

/**
 * Seed data for 50 yoga/stretch exercises
 * Images are stored as identifiers that map to local assets
 * See utils/exercise-images.ts for the actual image mapping
 */
export const EXERCISES_SEED_DATA: NewExercise[] = [
  {
    id: "downward-dog",
    title: "Chien tête en bas",
    image: "downward-dog",
    difficulties: [2, 3],
  },
  {
    id: "child-pose",
    title: "Posture de l'enfant",
    image: "child-pose",
    difficulties: [1, 2],
  },
  {
    id: "cat-cow",
    title: "Chat-vache",
    image: "cat-cow",
    difficulties: [1, 2],
  },
  {
    id: "warrior-1",
    title: "Guerrier 1",
    image: "warrior",
    difficulties: [2, 3],
  },
  {
    id: "warrior-2",
    title: "Guerrier 2",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "triangle-pose",
    title: "Triangle",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "tree-pose",
    title: "Arbre",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "mountain-pose",
    title: "Montagne",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "forward-fold",
    title: "Pliage avant",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "cobra-pose",
    title: "Cobra",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "bridge-pose",
    title: "Pont",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "seated-twist",
    title: "Torsion assise",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "pigeon-pose",
    title: "Pigeon",
    image: "default",
    difficulties: [1, 2, 3],
  },
  {
    id: "happy-baby",
    title: "Bébé heureux",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "corpse-pose",
    title: "Savasana",
    image: "default",
    difficulties: [1, 2, 3],
  },
  {
    id: "sun-salutation",
    title: "Salutation au soleil",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "half-lotus",
    title: "Demi-lotus",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "butterfly-stretch",
    title: "Papillon",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "seated-forward-bend",
    title: "Pliage assis",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "spinal-twist",
    title: "Torsion vertébrale",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "neck-stretch",
    title: "Étirement du cou",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "shoulder-rolls",
    title: "Roulades d'épaules",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "hip-circles",
    title: "Cercles de hanches",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "ankle-rolls",
    title: "Roulades de chevilles",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "wrist-stretch",
    title: "Étirement des poignets",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "calf-stretch",
    title: "Étirement mollets",
    image: "default",
    difficulties: [1, 2, 3],
  },
  {
    id: "quad-stretch",
    title: "Étirement quadriceps",
    image: "default",
    difficulties: [1, 2, 3],
  },
  {
    id: "hamstring-stretch",
    title: "Étirement ischio-jambiers",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "hip-flexor-stretch",
    title: "Étirement fléchisseurs",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "chest-opener",
    title: "Ouverture de poitrine",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "standing-side-stretch",
    title: "Étirement latéral debout",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "shoulder-stretch",
    title: "Étirement des épaules",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "triceps-stretch",
    title: "Étirement triceps",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "figure-four-stretch",
    title: "Étirement figure 4",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "lizard-pose",
    title: "Lézard",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "low-lunge",
    title: "Fente basse",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "high-lunge",
    title: "Fente haute",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "warrior-3",
    title: "Guerrier 3",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "extended-side-angle",
    title: "Angle latéral étendu",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "wide-legged-forward-fold",
    title: "Pliage jambes écartées",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "pyramid-pose",
    title: "Pyramide",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "camel-pose",
    title: "Chameau",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "bow-pose",
    title: "Arc",
    image: "default",
    difficulties: [2, 3],
  },
  {
    id: "locust-pose",
    title: "Sauterelle",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "sphinx-pose",
    title: "Sphinx",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "supine-twist",
    title: "Torsion allongée",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "legs-up-wall",
    title: "Jambes au mur",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "reclined-bound-angle",
    title: "Angle lié allongé",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "knee-to-chest",
    title: "Genou à la poitrine",
    image: "default",
    difficulties: [1, 2],
  },
  {
    id: "seated-side-bend",
    title: "Flexion latérale assise",
    image: "default",
    difficulties: [1, 2],
  },
];
