import { ExerciceEntity } from "@/libs/drizzle/database/exercice-entity";

// Mock data for 30 yoga/stretch exercises
export const MOCK_EXERCISES: ExerciceEntity[] = [
  {
    id: "downward-dog",
    title: "Chien tête en bas",
    image: "https://picsum.photos/800",
    difficulties: [2, 3],
  },
  {
    id: "child-pose",
    title: "Posture de l'enfant",
    image: "https://picsum.photos/800",
    difficulties: [2, 3],
  },
  { id: "cat-cow", title: "Chat-vache", image: "https://picsum.photos/800", difficulties: [1, 2] },
  {
    id: "warrior-1",
    title: "Guerrier 1",
    image: "https://picsum.photos/800",
    difficulties: [1, 2],
  },
  {
    id: "warrior-2",
    title: "Guerrier 2",
    image: "https://picsum.photos/800",
    difficulties: [2, 3],
  },
  {
    id: "triangle-pose",
    title: "Triangle",
    image: "https://picsum.photos/800",
    difficulties: [2, 3],
  },
  { id: "tree-pose", title: "Arbre", image: "https://picsum.photos/800", difficulties: [1, 2] },
  {
    id: "mountain-pose",
    title: "Montagne",
    image: "https://picsum.photos/800",
    difficulties: [1, 2],
  },
  {
    id: "forward-fold",
    title: "Pliage avant",
    image: "https://picsum.photos/800",
    difficulties: [2, 3],
  },
  { id: "cobra-pose", title: "Cobra", image: "https://picsum.photos/800", difficulties: [1, 2] },
  { id: "bridge-pose", title: "Pont", image: "https://picsum.photos/800", difficulties: [2, 3] },
  {
    id: "seated-twist",
    title: "Torsion assise",
    image: "https://picsum.photos/800",
    difficulties: [2, 3],
  },
  {
    id: "pigeon-pose",
    title: "Pigeon",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "happy-baby",
    title: "Bébé heureux",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "corpse-pose",
    title: "Corpse",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "sun-salutation",
    title: "Salutation au soleil",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "half-lotus",
    title: "Demi-lotus",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "butterfly-stretch",
    title: "Papillon",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "seated-forward-bend",
    title: "Pliage assis",
    image: "https://picsum.photos/800",
    difficulties: [1, 2],
  },
  {
    id: "spinal-twist",
    title: "Torsion vertébrale",
    image: "https://picsum.photos/800",
    difficulties: [1, 2],
  },
  {
    id: "neck-stretch",
    title: "Étirement du cou",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "shoulder-rolls",
    title: "Roulades d'épaules",
    image: "https://picsum.photos/800",
    difficulties: [2, 3],
  },
  {
    id: "hip-circles",
    title: "Cercles de hanches",
    image: "https://picsum.photos/800",
    difficulties: [1, 2],
  },
  {
    id: "ankle-rolls",
    title: "Roulades de chevilles",
    image: "https://picsum.photos/800",
    difficulties: [1, 2],
  },
  {
    id: "wrist-stretch",
    title: "Étirement des poignets",
    image: "https://picsum.photos/800",
    difficulties: [1, 2],
  },
  {
    id: "calf-stretch",
    title: "Étirement mollets",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "quad-stretch",
    title: "Étirement quadriceps",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "hamstring-stretch",
    title: "Étirement ischio-jambiers",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "hip-flexor-stretch",
    title: "Étirement fléchisseurs",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "chest-opener",
    title: "Ouverture de poitrine",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "chest-opener-2",
    title: "Ouverture de poitrine 2",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "chest-opener-3",
    title: "Ouverture de poitrine3",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "chest-opener-4",
    title: "Ouverture de poitrine 4",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "chest-opener-5",
    title: "Ouverture de poitrine 5 ",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "chest-opener-6",
    title: "Ouverture de poitrine 6",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "chest-opener-7",
    title: "Ouverture de poitrine 7 ",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "chest-opener-8",
    title: "Ouverture de poitrine 8",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
  {
    id: "chest-opener-9",
    title: "Ouverture de poitrine 9",
    image: "https://picsum.photos/800",
    difficulties: [1, 2, 3],
  },
];
